# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCi3VTnTgcXyUx83oPQMb0sbwj7w8bjj
"""

import streamlit as st

# Define the Streamlit app
def main():
    st.title("Maize Price and Weather Prediction in Kenya")

    # Input fields
    year = st.number_input('Year', min_value=2000, max_value=2100, step=1)
    month = st.number_input('Month', min_value=1, max_value=12, step=1)
    amount_produced = st.number_input('Amount Produced (scaled)', min_value=-3.0, max_value=3.0, step=0.1)
    annual_rainfall = st.number_input('Annual Rainfall (scaled)', min_value=-3.0, max_value=3.0, step=0.1)
    annual_temperature = st.number_input('Annual Temperature (scaled)', min_value=-3.0, max_value=3.0, step=0.1)

    # Predict button
    if st.button('Predict'):
        # Predict maize price
        price_prediction = price_model.predict([[year, month, amount_produced, annual_rainfall, annual_temperature]])
        st.write(f'Predicted Maize Price: {price_prediction[0][0]}')

        # Predict weather
        weather_prediction = weather_model.predict([[year, month]])
        st.write(f'Predicted Annual Rainfall: {weather_prediction[0][0]}')
        st.write(f'Predicted Annual Temperature: {weather_prediction[0][1]}')

# Run the Streamlit app
if __name__ == '__main__':
    main()